// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0s3egwWTpJ2XYO_jX7jukR1ZkTo6TTao',
    appId: '1:407748643875:web:b6f52902cfcae52262f596',
    messagingSenderId: '407748643875',
    projectId: 'chata-9df11',
    authDomain: 'chata-9df11.firebaseapp.com',
    storageBucket: 'chata-9df11.appspot.com',
    measurementId: 'G-71BP8YXRFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdizwdpyuPr0iwMPxAQjCE2rv88EGgTZI',
    appId: '1:407748643875:android:275d697345e8dff862f596',
    messagingSenderId: '407748643875',
    projectId: 'chata-9df11',
    storageBucket: 'chata-9df11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOKsQ4v5wM5bClX4rN7kGoUi4W5sYsClY',
    appId: '1:407748643875:ios:9cd47438882acbf762f596',
    messagingSenderId: '407748643875',
    projectId: 'chata-9df11',
    storageBucket: 'chata-9df11.appspot.com',
    iosBundleId: 'com.example.chata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOKsQ4v5wM5bClX4rN7kGoUi4W5sYsClY',
    appId: '1:407748643875:ios:9cd47438882acbf762f596',
    messagingSenderId: '407748643875',
    projectId: 'chata-9df11',
    storageBucket: 'chata-9df11.appspot.com',
    iosBundleId: 'com.example.chata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0s3egwWTpJ2XYO_jX7jukR1ZkTo6TTao',
    appId: '1:407748643875:web:6698e10b50baea3362f596',
    messagingSenderId: '407748643875',
    projectId: 'chata-9df11',
    authDomain: 'chata-9df11.firebaseapp.com',
    storageBucket: 'chata-9df11.appspot.com',
    measurementId: 'G-L2XJFNBNWT',
  );

}